config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
   
  root "pages#home"
 
  devise_for :users

  resources :quotes do
    resources :line_item_dates, except: [:index, :show] do
      resources :line_items, except: [:index, :show]   
    end
  end
end

app/models/quote.rb
class Quote < ApplicationRecord
    validates :name, presence: true

    scope :ordered, -> { order(id: :desc) }
    
    has_many :line_item_dates, dependent: :destroy
    
    has_many :line_items, through: :line_item_dates

    
    belongs_to :user

    
    # Following are the 3 ways to write a broadcasting function
    
    # after_create_commit -> { broadcast_prepend_to "quotes", partial: "quotes/quote", locals: { quote: self }, target: "quotes" }
    # after_create_commit -> { broadcast_prepend_to "quotes", partial: "quotes/quote", locals: { quote: self } }
    # after_create_commit -> { broadcast_prepend_to "quotes" }
    
    # Following are 3 broadcasts we require for each action (create, update, delete)
    
    # after_create_commit -> { broadcast_prepend_to "quotes" }
    # after_update_commit -> { broadcast_replace_to "quotes" }
    # after_destroy_commit -> { broadcast_remove_to "quotes" }
    
    #Using _later makes the broadcasting asynchrounous, making the webpage more efficient, as the method is applied first on the page of user performing, and then later reflected to the other user on the same page, not simultaneously.
    
    # after_create_commit -> { broadcast_prepend_later_to "quotes" }
    # after_update_commit -> { broadcast_replace_later_to "quotes" }
    # after_destroy_commit -> { broadcast_remove_to "quotes" }
    
    #Following is a one line code that performs the method of all three written above
    
    # broadcasts_to ->(quote) { "quotes" }, inserts_by: :prepend
    
    #Follwing only broadcasts to the same users
    
    broadcasts_to ->(quote) { [quote.user, "quotes"] }, inserts_by: :prepend
    
    def total_price
        line_items.sum(&:total_price)
      end
      
      def self.ransackable_attributes(auth_object = nil)
        # Replace these with the attributes you want to allow searching
        ["name", "id_value", "created_at"] 
      end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  def index
    @q = current_user.quotes.ordered.ransack(params[:q])
    # @quotes = @q.result

    @pagy, @quotes = pagy(@q.result, items: 10)


    # @quotes = current_user.quotes.ordered
  end
  
  def show
    @line_item_dates = @quote.line_item_dates.ordered
  end

  def new
    @quote = Quote.new
  end

  def create
      @quote = Quote.new(quote_params)
      @quote.user_id = current_user.id
    if @quote.save
      current_user.send_quote_created_notification(@quote)

      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote was successfully created." }
        format.turbo_stream { flash.now[:notice] = "Quote was successfully created." }

      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @quote.update(quote_params)
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote was successfully updated." }
        format.turbo_stream { flash.now[:notice] = "Quote was successfully updated." }
      end

    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @quote.destroy
  
    respond_to do |format|
      format.html { redirect_to quotes_path, notice: "Quote was successfully destroyed." }
      format.turbo_stream { flash.now[:notice] = "Quote was successfully destroyed." }

    end
  end

private

  def set_quote
    @quote = Quote.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:name)
  end

end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_empty_state.html.erb
<div class="empty-state">
  
  <p class="empty-state__text">
    You don't have any quotes yet!
  </p>

  <%= link_to "Add quote", new_quote_path, class: "btn btn--primary" %>

</div>

app/views/quotes/_form.html.erb
<%= simple_form_for quote, html: { class: "quote form" } do |f| %>

  <% if quote.errors.any? %>

    <div class="error-message">
      <%= quote.errors.full_messages.to_sentence.capitalize %>
    </div>

  <% end %>

  <%= f.input :name, input_html: { autofocus: true } %>

  <%= link_to "Cancel", quotes_path, class: "btn btn--light" %>

  <%= f.submit class: "btn btn--secondary" %>

<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag quote do %>

  <div class="quote">

    <%= link_to quote.name,
                quote_path(quote),
                data: { turbo_frame: "_top" } %>

    <div class="quote__actions">
      <%= button_to "Delete",
                    quote_path(quote),
                    method: :delete,
                    class: "btn btn--light" %>

      <%= link_to "Edit",
                  edit_quote_path(quote),
                  class: "btn btn--light" %>
    </div>

  </div>

  <br>

<% end %>

app/views/quotes/_total.html.erb
<footer class="quote-total">
  <div class="quote-total__inner container">
    <div>Total:</div>
    <div><%= number_to_currency quote.total_price %></div>
  </div>
</footer>

app/views/quotes/create.turbo_stream.erb
<%= turbo_stream.prepend "quotes", @quote %>
<%= turbo_stream.update Quote.new, "" %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove @quote %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>




<% if current_user.quotes.none? %>

  <%= turbo_stream.update Quote.new do %>

    <%= render "quotes/empty_state" %>

  <% end %>
  
<% end %>

app/views/quotes/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quote"), quote_path(@quote) %>

  <div class="header">
    <h1>
      Edit Quote
    </h1>
  </div>

  <%= turbo_frame_tag @quote do %>
    <%= render "form", quote: @quote %>
  <% end %>

</main>

app/views/quotes/index.html.erb
<%= turbo_stream_from current_user, "quotes" %>
  
  <main class="container">
  
  
      <div class="header">
        
        <h1>
          Quotes
        </h1>

        <%= link_to "New quote",
                    new_quote_path,
                    class: "btn btn--primary",
                    data: { turbo_frame: dom_id(Quote.new) } %>
      
      </div>
      
      <br>

      <div class="search-bar">  
        <%= search_form_for @q, url: quotes_path, method: :get, remote: true do |f| %>
            <%= f.text_field :name_cont, class: "search-field" ,  placeholder: "     Enter Quote Name" %>
            <%= f.submit "Search", class: "search-button btn btn--primary" %>
        <% end %>
      </div>        


        
       
      <br>

      <%= turbo_frame_tag Quote.new do %>
        
        <% if @quotes.none? %>
          <%= render "quotes/empty_state" %>          
        <% end %>
        


      <% end %>

      <%= turbo_frame_tag "quotes" do %>
   
        <%= render @quotes %>
      
      <% end %>
   
   

  </main>


  <%== pagy_nav(@pagy) %>


<%# render partial: 'pagy/nav', locals: { pagy: @pagy } %>

app/views/quotes/new.html.erb
<main class="container">
 
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>

  <div class="header">
    <h1>
      New quote
    </h1>
  </div>

  <%= turbo_frame_tag @quote do %>
    
    <%= render "form", quote: @quote %>
 
  <% end %>

</main>

app/views/quotes/show.html.erb
<main class="container mb-xxxxl">

  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
  
  <div class="header">
  
    <h1>
      <%= @quote.name %>
    </h1>
  
    <%= link_to 'New Date',
                new_quote_line_item_date_path(@quote),
                data: { turbo_frame: dom_id(LineItemDate.new) },
                class: "btn btn--primary" %>

  </div>
  
  <%= turbo_frame_tag LineItemDate.new %>


  <%= turbo_frame_tag "line_item_dates" do %>
   <%= render @line_item_dates, quote: @quote %>
  <% end %>

</main>

<%= turbo_frame_tag dom_id(@quote, :total) do %>
  <%= render "quotes/total", quote: @quote %>
<% end %>

app/views/quotes/update.turbo_stream.erb
<%= turbo_stream.replace @quote %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>